name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "hello-action"

      - if: ${{ !env.ACT }}
        uses: bahmutov/npm-install@v1

      - if: ${{ env.ACT }}
        working-directory: "hello-action"
        run: npm i

      - if: ${{ !env.ACT }}
        run: npm run build

      - if: ${{ env.ACT }}
        run: npm run build
        working-directory: "hello-action"

      - uses: ./
